use_frameworks!

platform :ios, '12.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'

  post_install do |installer|
       installer.generated_projects.each do |project|
         project.targets.each do |target|
             target.build_configurations.each do |config|
                 config.build_settings['CODE_SIGN_IDENTITY'] = ''
              end
         end
       end
       installer.pods_project.build_configurations.each do |config|
               config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
           end
       installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
               config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
           end
       end
   end
	
end
